import { OptimizationItem } from '../types';

export const DEFAULT_OPTIMIZATIONS: OptimizationItem[] = [
  {
    id: 'telemetry_diagtrack',
    category: 'telemetry',
    title: 'Disable DiagTrack & Telemetry Services',
    description: 'Stops and disables Connected User Experiences and Telemetry service (DiagTrack).',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: 'Stop-Service -Name DiagTrack; Set-Service -Name DiagTrack -StartupType Disabled',
    undoCommand: 'Set-Service -Name DiagTrack -StartupType Automatic; Start-Service -Name DiagTrack',
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'telemetry_dmwappush',
    category: 'telemetry',
    title: 'Disable dmwappushservice',
    description: 'Disables WAP Push Message Routing Service used for telemetry diagnostics collection.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: 'Stop-Service -Name dmwappushservice; Set-Service -Name dmwappushservice -StartupType Disabled',
    undoCommand: 'Set-Service -Name dmwappushservice -StartupType Demand',
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'telemetry_ceip_tasks',
    category: 'telemetry',
    title: 'Disable CEIP Scheduled Telemetry Tasks',
    description: 'Disables Customer Experience Improvement Program scheduled tasks in Task Scheduler.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "Disable-ScheduledTask -TaskPath '\\Microsoft\\Windows\\Customer Experience Improvement Program\\' -TaskName 'Consolidator' -ErrorAction SilentlyContinue; Disable-ScheduledTask -TaskPath '\\Microsoft\\Windows\\Customer Experience Improvement Program\\' -TaskName 'UsbCeip' -ErrorAction SilentlyContinue",
    undoCommand: "Enable-ScheduledTask -TaskPath '\\Microsoft\\Windows\\Customer Experience Improvement Program\\' -TaskName 'Consolidator' -ErrorAction SilentlyContinue; Enable-ScheduledTask -TaskPath '\\Microsoft\\Windows\\Customer Experience Improvement Program\\' -TaskName 'UsbCeip' -ErrorAction SilentlyContinue",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'bloatware_cortana',
    category: 'bloatware',
    title: 'Disable Cortana App & Background Execution',
    description: 'Disables Cortana autostart and background task execution via group policy registry key.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search' -Name 'AllowCortana' -Value 0 -Type DWord -Force",
    undoCommand: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search' -Name 'AllowCortana' -Value 1 -Type DWord -Force",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'bloatware_onedrive',
    category: 'bloatware',
    title: 'Uninstall OneDrive Integration',
    description: 'Removes standalone OneDrive client and unbinds Explorer cloud integration.',
    riskLevel: 'medium',
    isReversible: false,
    powershellCommand: "Stop-Process -Name OneDrive -ErrorAction SilentlyContinue; $setup = Join-Path $env:SystemRoot 'SysWOW64\\OneDriveSetup.exe'; if (-not (Test-Path $setup)) { $setup = Join-Path $env:SystemRoot 'System32\\OneDriveSetup.exe' }; if (Test-Path $setup) { Start-Process $setup -ArgumentList '/uninstall' -Wait }",
    undoCommand: '# Manual reinstallation required via OneDrive setup binary',
    isRecommended: false,
    isSelected: false,
  },
  {
    id: 'bloatware_xbox_apps',
    category: 'bloatware',
    title: 'Remove Xbox Companion & Game Overlay Apps',
    description: 'Uninstalls Xbox Companion and Game Bar AppX packages for non-gaming Windows installations.',
    riskLevel: 'medium',
    isReversible: true,
    powershellCommand: 'Get-AppxPackage -AllUsers *XboxApp* | Remove-AppxPackage -ErrorAction SilentlyContinue',
    undoCommand: 'Get-AppxPackage -AllUsers *XboxApp* | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\\AppXManifest.xml"}',
    isRecommended: false,
    isSelected: false,
  },
  {
    id: 'bloatware_3d_viewer',
    category: 'bloatware',
    title: 'Remove 3D Viewer & Mixed Reality Apps',
    description: 'Removes 3D Viewer and Mixed Reality Portal provisioned packages.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: 'Get-AppxPackage *Microsoft3DViewer* | Remove-AppxPackage -ErrorAction SilentlyContinue',
    undoCommand: '# Reinstall via Microsoft Store',
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'privacy_advertising_id',
    category: 'privacy',
    title: 'Disable Advertising ID for Apps',
    description: 'Prevents apps from using advertising ID for tailored ads across application sessions.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo' -Name 'Enabled' -Value 0 -Type DWord -Force",
    undoCommand: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo' -Name 'Enabled' -Value 1 -Type DWord -Force",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'privacy_location_tracking',
    category: 'privacy',
    title: 'Disable System Location Tracking Services',
    description: 'Turns off global OS location service access and location history logging.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location' -Name 'Value' -Value 'Deny' -Type String -Force",
    undoCommand: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location' -Name 'Value' -Value 'Allow' -Type String -Force",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'privacy_activity_history',
    category: 'privacy',
    title: 'Disable Activity History & Cloud Sync',
    description: 'Stops collecting user activity history and prevents cloud timeline synchronization.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System' -Name 'PublishUserActivities' -Value 0 -Type DWord -Force",
    undoCommand: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System' -Name 'PublishUserActivities' -Value 1 -Type DWord -Force",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'services_sysmain',
    category: 'services',
    title: 'Disable SysMain (Superfetch) Service',
    description: 'Stops SysMain service to reduce excessive disk read/write cycles on NVMe/SSD drives.',
    riskLevel: 'medium',
    isReversible: true,
    powershellCommand: 'Stop-Service -Name SysMain; Set-Service -Name SysMain -StartupType Disabled',
    undoCommand: 'Set-Service -Name SysMain -StartupType Automatic; Start-Service -Name SysMain',
    isRecommended: false,
    isSelected: false,
  },
  {
    id: 'services_search_indexing',
    category: 'services',
    title: 'Set Windows Search Indexing to Manual',
    description: 'Configures Windows Search (WSearch) service startup type to Manual to avoid background CPU spikes.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: 'Set-Service -Name WSearch -StartupType Manual',
    undoCommand: 'Set-Service -Name WSearch -StartupType Automatic; Start-Service -Name WSearch',
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'services_fax_spooler',
    category: 'services',
    title: 'Disable Fax & Legacy Print Services',
    description: 'Disables Fax service and disables automatic legacy print spooler background scanning.',
    riskLevel: 'medium',
    isReversible: true,
    powershellCommand: 'Stop-Service -Name Fax -ErrorAction SilentlyContinue; Set-Service -Name Fax -StartupType Disabled',
    undoCommand: 'Set-Service -Name Fax -StartupType Manual',
    isRecommended: false,
    isSelected: false,
  },
  {
    id: 'ui_show_file_extensions',
    category: 'ui_tweaks',
    title: 'Show File Extensions in Explorer',
    description: 'Forces Windows File Explorer to display file extension suffixes for all known file types.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced' -Name 'HideFileExt' -Value 0 -Type DWord -Force",
    undoCommand: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced' -Name 'HideFileExt' -Value 1 -Type DWord -Force",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'ui_show_hidden_files',
    category: 'ui_tweaks',
    title: 'Show Hidden Files & Folders',
    description: 'Configures File Explorer to reveal hidden files, system directories, and hidden items.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced' -Name 'Hidden' -Value 1 -Type DWord -Force",
    undoCommand: "Set-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced' -Name 'Hidden' -Value 2 -Type DWord -Force",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'ui_classic_context_menu',
    category: 'ui_tweaks',
    title: 'Restore Classic Windows 10 Right-Click Context Menu',
    description: 'Restores classic context menu in Windows 11 Explorer without requiring Shift+F10.',
    riskLevel: 'low',
    isReversible: true,
    powershellCommand: "New-Item -Path 'HKCU:\\Software\\Classes\\CLSID\\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\\InprocServer32' -Value '' -Force",
    undoCommand: "Remove-Item -Path 'HKCU:\\Software\\Classes\\CLSID\\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}' -Recurse -Force -ErrorAction SilentlyContinue",
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'disk_clean_temp',
    category: 'disk_cleanup',
    title: 'Purge System & User Temp Directories',
    description: 'Safely removes temporary files and cache artifacts from Windows Temp and User Temp folders.',
    riskLevel: 'low',
    isReversible: false,
    powershellCommand: 'Remove-Item -Path "$env:TEMP\\*" -Recurse -Force -ErrorAction SilentlyContinue; Remove-Item -Path "$env:SystemRoot\\Temp\\*" -Recurse -Force -ErrorAction SilentlyContinue',
    undoCommand: '# Temp file deletion is permanent and cannot be undone',
    isRecommended: true,
    isSelected: true,
  },
  {
    id: 'disk_clean_delivery_optimization',
    category: 'disk_cleanup',
    title: 'Flush Delivery Optimization Cache',
    description: 'Clears residual Windows Update Delivery Optimization cache files to free storage space.',
    riskLevel: 'low',
    isReversible: false,
    powershellCommand: 'Delete-DeliveryOptimizationCache -ErrorAction SilentlyContinue',
    undoCommand: '# Cache flush cannot be undone',
    isRecommended: true,
    isSelected: true,
  },
];
